# Generated by Django 3.2.3 on 2021-06-08 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 8, 15, 9, 32, 658412, tzinfo=utc), verbose_name='date joined'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
    ]
