# Generated by Django 3.2.3 on 2021-06-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210608_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='Phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
